# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projets\Scripts\Python\Mew\Inteface Qt5\mew.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 71, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\Projets\\Scripts\\Python\\Mew\\Inteface Qt5\\../logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(310, 150, 75, 23))
        self.btn_stop.setObjectName("btn_stop")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(270, 10, 111, 91))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.text_log = QtWidgets.QTextEdit(self.centralwidget)
        self.text_log.setGeometry(QtCore.QRect(10, 10, 251, 91))
        self.text_log.setObjectName("text_log")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 150, 61, 21))
        self.label_2.setObjectName("label_2")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(220, 150, 75, 23))
        self.btn_start.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.btn_start.setCheckable(False)
        self.btn_start.setAutoDefault(False)
        self.btn_start.setDefault(False)
        self.btn_start.setFlat(False)
        self.btn_start.setObjectName("btn_start")
        self.btn_test = QtWidgets.QPushButton(self.centralwidget)
        self.btn_test.setGeometry(QtCore.QRect(310, 110, 75, 23))
        self.btn_test.setObjectName("btn_test")
        self.spinBox_minutes = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_minutes.setGeometry(QtCore.QRect(150, 150, 42, 22))
        self.spinBox_minutes.setObjectName("spinBox_minutes")
        self.btn_calib = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calib.setGeometry(QtCore.QRect(220, 110, 75, 23))
        self.btn_calib.setObjectName("btn_calib")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.label_2.setText(_translate("MainWindow", "Nb minutes"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_test.setText(_translate("MainWindow", "Test position"))
        self.btn_calib.setText(_translate("MainWindow", "Calibrage"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
